if SimulationFlag then goto SIMULATION end

SPose = DP_GET("DL0")
SPose = RPD_P1A1(2, 200, SPose, RPD_TCP_L_MU)
MOVE_WITH_DEFAULT_SPEED_AND_MID_POSE(SPose, TCP_MOVEPOSE_LIST)

TS_POINT = TOUCHSENSING_3F_Left(DirSearch)
TP_SAVE("PL0", TS_POINT)

goto FINISH

::SIMULATION:: 
TP_SAVE("PL0", RPD_TCP_L_MU)

::FINISH::

