if SimulationFlag then goto SIMULATION end

SPose = DP_GET("DR0")
SPose = RPD_P1A1(2, 200, SPose, RPD_TCP_R_MU)
MOVE_WITH_DEFAULT_SPEED_AND_MID_POSE(SPose, TCP_MOVEPOSE_LIST)

TS_POINT = TOUCHSENSING_3F_Right(DirSearch)
TP_SAVE("PR0", TS_POINT)

goto FINISH

::SIMULATION:: 
TP_SAVE("PR0", RPD_TCP_R_MU)

::FINISH::